#!/usr/bin/env ruby

username = "johnjoseph"

password = `security 2>&1 >/dev/null find-internet-password -g -s 'twitter.com' -a '#{username}' | cut -d '"' -f 2`.strip

message = ARGV[0]

print `
curl \
  --stderr '/dev/null' \
  --write-out "%{http_code}" \
  -u #{username}:#{password} \
  -d status='#{message}' \
  https://twitter.com/statuses/update.xml
`
